spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/online-library
    password: 2201
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true